#!/bin/bash


echo "Formatting Code"
./gradlew app:formatKotlin
echo "Checking code formatting"

./gradlew app:lintKotlin --daemon

STATUS=$?

if [ "$STATUS" = 0 ]; then
  echo "No formatting issues were found"
  exit 0
else
  echo 1>&2 "* There are code formatting issues that must be addressed"
  echo "Try using './gradlew app:formatKotlin' to fix these issues automatically"
  exit 1
fi
