#!/bin/bash
echo "Running code formatting"

# Run the formatting task
./gradlew app:formatKotlin --daemon

FORMAT_STATUS=$?

# Check if formatting was successful
if [ "$FORMAT_STATUS" != 0 ]; then
  echo "Formatting failed. Please fix the formatting issues."
  exit 1
fi

# Add the changes resulting from formatting
git add .
git reset HEAD app/src/main/res/values/strings.xml



echo "Checking code formatting"

./gradlew app:lintKotlin --daemon

STATUS=$?

if [ "$STATUS" = 0 ]; then
  echo "No formatting issues were found"
  exit 0
else
  echo 1>&2 "* There are code formatting issues that must be addressed"
  echo "Try using './gradlew app:formatKotlin' to fix these issues automatically"
  exit 1
fi
